Repository BeyondPong/Backend, pull requests merged in 2024-06, with the labels that each got.

#33 [Feat] 유저 언어 설정 변경 api 추가
  backend/backend/settings.py
  backend/user/serializers.py
  backend/user/urls.py
  backend/user/views.py
Labels: feat

#42 [Feat] 로그인 jwt 구현
  backend/backend/settings.py
  backend/game/views.py
  backend/login/middleware.py
  backend/login/urls.py
  backend/login/views.py
  backend/requirements.txt
  backend/user/views.py
Labels: feat

#48 [Fix] jwt 에러 수정
  backend/backend/settings.py
  backend/login/authentication.py
  backend/login/middleware.py
Labels: bug

#51 [Feat] 친구 목록 조회 api 추가
  backend/backend/asgi.py
  backend/backend/settings.py
  backend/login/authentication.py
  backend/requirements.txt
  backend/user/consumers.py
  backend/user/serializers.py
  backend/user/urls.py
  backend/user/views.py
Labels: feat

#53 [Feat] 친구 삭제 api 추가
  backend/login/authentication.py
  backend/user/consumers.py
  backend/user/serializers.py
  backend/user/urls.py
  backend/user/views.py
Labels: feat

#56 [Refactor] 보여지는 nickname 수정
  backend/game/consumers.py
Labels: refactor

#57 [Feat] mode가 토너먼트일 때 닉네임 중복 검사 로직 구현
  backend/game/urls.py
  backend/game/views.py
Labels: feat

#59 [Feat] 2fa 구현
  backend/backend/settings.py
  backend/login/authentication.py
  backend/login/urls.py
  backend/login/views.py
Labels: feat

#61 [Refactor] 클라이언트 측 으로 보내는 로직 수정
  backend/game/consumers.py
  backend/game/views.py
Labels: refactor

#62 [Feat] GDPR 회원탈퇴 구현
  backend/login/authentication.py
  backend/login/views.py
  backend/user/urls.py
  backend/user/views.py
Labels: feat

#66 [Refactor] 회원가입 여부 추가
  backend/login/views.py
Labels: refactor

#67 [Feat] 게임 로직 수정
  backend/game/consumers.py
Labels: feat

#68 [Refactor]토너먼트 중복검사 API
  backend/game/consumers.py
  backend/game/urls.py
  backend/game/views.py
Labels: refactor

#71 [refactor] remote 게임 동작하게 rollback
  backend/game/consumers.py
Labels: refactor

#72 [Refactor] 게임 로직 수정
  backend/game/apps.py
  backend/game/consumers.py
  backend/game/utils.py
Labels: refactor

#73 [Refactor] 닉네임 중복 검사 Response값 수정
  backend/game/consumers.py
  backend/game/serializers.py
  backend/game/urls.py
  backend/game/views.py
Labels: refactor

#74 [Feat] 회원가입 여부 api 추가
  backend/login/authentication.py
  backend/login/urls.py
  backend/login/views.py
Labels: feat

#76 [Refactor] game 결과 입력 request 수정
  backend/game/serializers.py
  backend/game/views.py
Labels: refactor

#79 [Fix] game paddle 버그 수정
  backend/game/consumers.py
Labels: bug

#81 [Refactor] 토너먼트 닉네임 중복검사
  backend/game/consumers.py
  backend/game/views.py
Labels: refactor

#83 [Feat] 게임 재시작 로직 추가
  backend/game/consumers.py
Labels: feat

#84 [Refactor] 중복된 부분 삭제
  backend/game/consumers.py
Labels: refactor

#88 [Refactor] 게임 재시작 로직 수정
  backend/game/consumers.py
Labels: refactor

#89 [Refactor] 토너먼트용 nickname 변수 변경
  backend/game/consumers.py
Labels: refactor

#91 [Feat] 게임 시작할 때 windows 세팅
  backend/game/apps.py
  backend/game/consumers.py
Labels: feat

#95 [Feat] 토너먼트 모드에 4명 차면 game_start 보내는 로직 추가
  backend/game/consumers.py
Labels: feat

#97 [Refactor] running_user 관련 로직 수정
  backend/game/consumers.py
Labels: refactor

#98 [Feat] tournament 게임을 위해 players와 spctators 역할 부여 및 remote 게임 적용
  backend/game/consumers.py
Labels: feat

#103 [Refactor] 로그인 2FA 기능 변경
  backend/login/views.py
Labels: refactor

#104 [Feat] 게임 나갈때 몰수패 기능 추가
  backend/game/consumers.py
Labels: enhancement

#105 [Feat] 토너먼트 다음 라운드 로직 구현
  backend/game/apps.py
  backend/game/consumers.py
Labels: enhancement

#109 [Refactor] 토너먼트 닉네임 관리 로직 수정
  backend/game/consumers.py
Labels: refactor

#110 [Feat] 토너먼트 진행 로직 추가
  backend/game/consumers.py
Labels: enhancement

#111 [Feat] 결승 게임 로직 추가
  backend/game/consumers.py
Labels: enhancement

#114 [Feat] 직전 게임에서 이긴 사람에게 공 먼저 가게 처리
  backend/game/consumers.py
Labels: enhancement

#115 [Feat] 토너먼트 몰수패 처리
  backend/game/consumers.py
  backend/login/views.py
Labels: feat

#117 [Fix] 몰수패 처리 수정
  backend/game/consumers.py
Labels: bug

#118 [Refactor] 토너먼트 게임 중복 로직 수정
  backend/game/consumers.py
Labels: refactor
