Repository BeyondPong/Backend, pull requests merged in 2024-07, with the labels that each got.

#119 [Feat] paddle에 color속성 추가
  backend/game/consumers.py
Labels: enhancement

#122 [Feat] 게임방에 최대 인원보다 작으면 그 방으로 찾아 들어가는 이슈 해결
  backend/game/consumers.py
  backend/game/utils.py
Labels: feat

#123 [Fix] disconnect시 spectators에 쌓이는 문제 해결
  backend/game/consumers.py
Labels: bug

#126 [Refactor] 참가자 목록 관리
  backend/game/consumers.py
Labels: refactor

#127 [Fix] update_score에서 2초 쉴 때 게임 종료되지 않는 문제 해결
  backend/game/consumers.py
Labels: bug

#129 [Bug] 토너먼트 닉네임 입력 순서에 따른 문제
  backend/game/consumers.py
Labels: bug

#131 [Feat] 다중 로그인 체크 api 추가
  backend/login/urls.py
  backend/login/views.py
Labels: enhancement

#133 [Refactor] 다중 로그인 jwt 검증단계 예외 처리
  backend/backend/settings.py
  backend/login/authentication.py
  backend/login/urls.py
  backend/login/views.py
Labels: refactor

#134 [Feat] 여러 경우에 대한 에러처리 추가
  backend/backend/settings.py
  backend/game/consumers.py
Labels: enhancement

#135 [Feat] login redirect_url 보내주는 api 추가
  backend/login/views.py
Labels: feat
